/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.table.DefaultTableModel;
import modelo.*;
import controlador.*;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class frmViaje extends javax.swing.JFrame {

    negocio obj = new negocio();

    /**
     * Creates new form frmViaje
     */
    public frmViaje() {
        initComponents();
        muestraRutas();
    }

    void muestraRutas() {
        cbRutas.removeAllItems();
        for (Ruta x : obj.ListRuta()) {
            cbRutas.addItem(x.getRutnom());
        }
    }

    void muestraViaje(String cod) {
        DefaultTableModel dt = (DefaultTableModel) tab_Viaje.getModel();
        dt.setRowCount(0);
        for (Viaje x : obj.ListViaje(cod)) {
            Object v[] = {x.getVianro(), x.getViafh(), x.getCostvia()};
            dt.addRow(v);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbRutas = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab_Viaje = new javax.swing.JTable();
        lbimg = new javax.swing.JLabel();
        btnVERPASA = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("SELECCIONE RUTA");

        cbRutas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbRutas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbRutasItemStateChanged(evt);
            }
        });
        cbRutas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbRutasActionPerformed(evt);
            }
        });

        tab_Viaje.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "VIAJE", "FECHA", "COSTO"
            }
        ));
        jScrollPane1.setViewportView(tab_Viaje);

        lbimg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255)));

        btnVERPASA.setText("VER PASAJEROS");
        btnVERPASA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVERPASAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addComponent(lbimg, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel1)
                        .addGap(54, 54, 54)
                        .addComponent(cbRutas, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(btnVERPASA)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbRutas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(lbimg, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(btnVERPASA)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbRutasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbRutasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbRutasActionPerformed

    private void cbRutasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbRutasItemStateChanged
        try {
            String cad = (String) cbRutas.getSelectedItem();
            imagen(cad);
            System.out.println("cadena:" + cad);
            muestraViaje(cad);
        } catch (Exception e) {
        }

    }//GEN-LAST:event_cbRutasItemStateChanged

    private void btnVERPASAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVERPASAActionPerformed
        int f = tab_Viaje.getSelectedRow();
        if (f == -1) {
            JOptionPane.showMessageDialog(null, "Elija una fila");
            return;
        } else {
            frmGrabar.nrovia = tab_Viaje.getValueAt(f, 0).toString();
            frmGrabar.ruta = (String) cbRutas.getSelectedItem();
            frmGrabar.costo = Double.parseDouble(tab_Viaje.getValueAt(f, 2).toString());
            frmGrabar fr = new frmGrabar();
            fr.setLocationRelativeTo(null);
            fr.setVisible(true);
            this.setVisible(false);
        }


    }//GEN-LAST:event_btnVERPASAActionPerformed
    void imagen(String cad) {
        ImageIcon imgIcon = new ImageIcon(getClass().getResource("/imagenes/" + cad + ".jpg"));
        //asignar la imagen con el tamaño de la etiqueta
        Image imgEscala = imgIcon.getImage().getScaledInstance(
                lbimg.getWidth(), lbimg.getHeight(), Image.SCALE_SMOOTH);
        //mostrar la imagen en la etiqueta
        //Icon iconoEscala= new ImageIcon(imgEscala);
        lbimg.setIcon(new ImageIcon(imgEscala));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmViaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmViaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmViaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmViaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmViaje().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVERPASA;
    public static javax.swing.JComboBox<String> cbRutas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbimg;
    public static javax.swing.JTable tab_Viaje;
    // End of variables declaration//GEN-END:variables
}
